[project]
name = "airmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air-convert>=0.2.0",
    "air[standard]>=0.21.0",
    "fastmcp>=2.11.3",
]
