[project]
name = "airmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air-convert>=0.3.0",
    "air[standard]>=0.23.0",
    "fastapi[standard]>=0.116.1",
    "fastmcp>=2.11.3",
]
